apiVersion: v2
name: mcp-google-server
description: Helm Chart for mcp-google-server
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: secret-storage
  version: 0.2.0
  repository: "@justworks"
  alias: secret-storage
- name: go-application
  version: 0.1.3
  repository: "@justworks"
  alias: mcp-google-server-service
