hostname: &hostname mcp-google-server-dev.nonprod.vibe.justworks.com

mcp-google-server-env: &env
  env:
    - name: NODE_ENV
      value: production
    - name: TRANSPORT
      value: http
    - name: PORT
      value: "3000"
    - name: GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: mcp-google-server-dev
          key: GOOGLE_CLIENT_ID
    - name: GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: mcp-google-server-dev
          key: GOOGLE_CLIENT_SECRET
    - name: GOOGLE_REDIRECT_URI
      value: https://mcp-google-server-dev.nonprod.vibe.justworks.com/callback

# Service
mcp-google-server-service:
  nameOverride: mcp-google-server-service-dev
  fullnameOverride: mcp-google-server-service-dev

  <<: *env

  serviceAccount:
    name: mcp-google-server-dev-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::974932714082:role/app/mcp-google-server-dev

  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:974932714082:certificate/b140e71a-626c-47d8-a33f-cc65e902856a
      external-dns.alpha.kubernetes.io/hostname: *hostname

    customPaths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: mcp-google-server-service-dev
            port:
              number: 3000
    hosts:
      - *hostname
    tls:
      - hosts:
          - *hostname

  autoscaling:
    enabled: false

  datadog:
    env: vibe-dev

secret-storage:
  nameOverride: mcp-google-server-secrets-dev
  fullnameOverride: mcp-google-server-secrets-dev
  serviceAccount:
    name: mcp-google-server-dev-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::974932714082:role/app/mcp-google-server-dev
  secretStore:
    name: mcp-google-server-dev
    secrets:
      - secretKey: GOOGLE_CLIENT_ID
        remoteRef:
          key: mcp-google-server-dev/app
          property: GOOGLE_CLIENT_ID
      - secretKey: GOOGLE_CLIENT_SECRET
        remoteRef:
          key: mcp-google-server-dev/app
          property: GOOGLE_CLIENT_SECRET
