mcp-google-server-image: &image
  image:
    repository: 974932714082.dkr.ecr.us-east-1.amazonaws.com/mcp-google-server
    tag: latest
    pullPolicy: Always

mcp-google-server-service:
  nameOverride: mcp-google-server-service
  fullnameOverride: mcp-google-server-service

  <<: *image

  env: []

  command:
    - node
    - dist/index.js

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

  serviceAccount:
    create: false
    name: mcp-google-server-sa
    annotations:
      eks.amazonaws.com/role-arn: ""

  service:
    port: 3000

  ingress:
    enabled: false
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /health
    customPaths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: mcp-google-server-service
            port:
              number: 3000
    hosts: []
    tls:
      - hosts: []

  probes:
    startup:
      httpGet:
        path: /health
        port: 3000
    liveness:
      httpGet:
        path: /health
        port: 3000
    readiness:
      httpGet:
        path: /health
        port: 3000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 85
    behavior:
      scaleDown:
        policies:
          - type: Pods
            value: 1
            periodSeconds: 1200
        stabilizationWindowSeconds: 1200

  datadog:
    enabled: true
    service: mcp-google-server
    env: NA

  git:
    repository: https://github.com/justworkshr/mcp-google-server
