import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerListMessages } from './list_messages.js';
import { registerGetMessage } from './get_message.js';
import { registerSendEmail } from './send_email.js';
import { registerReplyEmail } from './reply_email.js';
import { registerListThreads } from './list_threads.js';
import { registerGetThread } from './get_thread.js';
import { registerModifyLabels } from './modify_labels.js';
import { registerListLabels } from './list_labels.js';
import { registerCreateDraft } from './create_draft.js';
import { registerListDrafts } from './list_drafts.js';
import { registerGetDraft } from './get_draft.js';
import { registerUpdateDraft } from './update_draft.js';
import { registerDeleteDraft } from './delete_draft.js';
import { registerOpenDraft } from './open_draft.js';
import { registerSendDraft } from './send_draft.js';
import { registerListFilters } from './list_filters.js';
import { registerGetFilter } from './get_filter.js';
import { registerCreateFilter } from './create_filter.js';
import { registerDeleteFilter } from './delete_filter.js';

export function registerGmailTools(server: McpServer): void {
  registerListMessages(server);
  registerGetMessage(server);
  registerSendEmail(server);
  registerReplyEmail(server);
  registerListThreads(server);
  registerGetThread(server);
  registerModifyLabels(server);
  registerListLabels(server);
  registerCreateDraft(server);
  registerListDrafts(server);
  registerGetDraft(server);
  registerUpdateDraft(server);
  registerDeleteDraft(server);
  registerOpenDraft(server);
  registerSendDraft(server);
  registerListFilters(server);
  registerGetFilter(server);
  registerCreateFilter(server);
  registerDeleteFilter(server);
}
