name: Build ECR Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ecr-image:
    name: Build ECR Image
    uses: justworkshr/actions/.github/workflows/ecr-build.yml@main
    permissions:
      contents: read
      pull-requests: write
    with:
      SERVICE_NAME: mcp-google-server
      AWS_ACCOUNT_ID: "974932714082"
      PUSH_IMAGE_TAG_ONLY: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.VIBE_NONPROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.VIBE_NONPROD_AWS_SECRET_ACCESS_KEY }}
      PRIVATE_REPO: ${{ secrets.PRIVATE_REPO }}
