name: Build ECR Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ecr-image:
    name: Build ECR Image
    uses: justworkshr/actions/.github/workflows/ecr-build-oidc.yml@main
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN_NONPROD }}
      SERVICE_NAME: mcp-google-server
      AWS_ACCOUNT_ID: "974932714082"
      PUSH_IMAGE_TAG_ONLY: true
    secrets:
      PRIVATE_REPO: ${{ secrets.PRIVATE_REPO }}
