name: Helm Validator
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  helm_validator:
    strategy:
      matrix:
        HELM_CHART_LOCATION: [helm/service]
    uses: justworkshr/actions/.github/workflows/chart-validator.yml@main
    secrets:
      JUSTWORKS_GHTOKEN: ${{ secrets.GH_PACKAGES }}
    with:
      HELM_CHART_LOCATION: ${{ matrix.HELM_CHART_LOCATION }}
      VALUES_ENVS: dev,staging,prod
